### PR TITLE
Add support for REG_LITE_SHOW_COMPANY_INPUT marketing setting

### PR DESCRIPTION
**Pull request by edwinfinch**
The company field may not be required in some cases. This commit adds support for the new REG_LITE_SHOW_COMPANY_INPUT setting, which allows the event admin to toggle whether or not they want the company field included in the registration lite component. 

**What kind of change does this PR introduce?**

Support for one additional setting

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Potentially needs further documentation if not already sufficient in the documentation added by me in other repos:
- showCompanyInput
- REG_LITE_SHOW_COMPANY_INPUT

### CODE REVIEW

**Comment by smarcet** [comment]
@edwinfinch please remove all json files from this commit
those should not be commited
regards

**Review by smarcet — CHANGES_REQUESTED** [review]
@edwinfinch please review comments

**Review by smarcet — COMMENTED** [review]
LGTM but we need the new version of reg lite widget published to merge this

**Comment by edwinfinch** [comment]
Should be good to go now

**Comment by smarcet** [comment]
@edwinfinch please update registration lite widget version to 4.0.10
here
https://github.com/OpenEventKit/eventsite/blob/becc6b23ad3dd220a47cf87e6f8a5cdafea45a83/package.json#L127
also u need to upload the updated yarn.lock file
much thanks!

**Review by smarcet — APPROVED** [review]
LGTM

**Pull request merged**
